version: "3"

services:
  start-dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mongo
      - rabbitmq
    command: rabbitmq:5672

  api:
    build: ../src/Actio.Api
    links:
      - rabbitmq
      - mongo
    ports:
      - '5049:5049'

  activities-service:
    build: ../src/Actio.Services.Activities
    links:
      - rabbitmq
      - mongo
    ports:
      - '5051:5051'

  identity-service:
    build: ../src/Actio.Services.Identity
    links:
      - rabbitmq
      - mongo
    ports:
      - '5052:5052'

  mongo:
    image: mongo
    volumes:
      - E:\docker\volumes\curso-pckt:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'